Map<String, dynamic> appLabels = {
  "loginScreen": {
    "welcomeToTaqa": "Welcom To TAQA BTMS",
    "loginToContinue": "Please Login to Continue",
    "emailPhone": "Email",
    "password": "Password",
    "loginWithFingerPrint": "Login With Finger Print",
    "forgotPassword": "Forgot Password?",
  },
  "RequestDetailsScreen": {
    "delete": "Delete",
    "editRequest": "Edit Request",
    "viewOptions": "View Options",
    "createCopy": "Create A Copy",
    "requestDetails": "Request Details",
    "submittedOn": "Submitted on :",
    "requisitionNumber": "Requisition Number",
    "travellerName": "Traveller Name",
    "departureDate": "Departure Date",
    "approvalTracking": "Approval Tracking",
    "requestStatus": "Request Status",
    "tmcStatus": "TMC Status",
    "optionSelection": "Option Selection",
  },
  "common": {
    "required": "Required",
    "login": "Login",
    "from": "From",
    "to": "To",
    "invalid": "Invalid Input",
    "invalidEmail": "Invalid Email Address",
  },
  "viewOptionScreen": {
    "travellerFirstName": "Traveller’s First Name",
    "travelLastName": "Traveller’s Last Name",
    "travelDepartment": "Travel Department",
    "gender": "Gender",
    "travelEmail": "Traveler Email",
    "travelerPhoneNumber": "Traveler’s phone number",
  },
};
